# -*- coding: utf-8 -*-
"""AI_ML_Exp_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Ishvajeetsingh/AI-ML-Experiments/blob/main/AI_ML_Exp_5.ipynb
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()


import io
df = pd.read_csv(io.BytesIO(uploaded['student-scores.csv']))

# General info about the dataset
df.info()

# Statistical summary
df.describe()

# Check missing values
df.isnull().sum()

df.isnull().sum()

df.describe()

df.info()