# -*- coding: utf-8 -*-
"""Exp 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jw1QhZxZHSnI0YFyU4cRSHfgSUQv-tj-

Experiment 4: write a python program to import and export data using Pandas and show
"""



uploaded = files.upload(Annual enterprise)

import io

df.head(5)

# prompt: Experiment 4: write a python program to import and export data using Pandas and show

import pandas as pd
from google.colab import files
import io

uploaded = files.upload()

df = pd.read_csv(io.BytesIO(uploaded['your_file.csv'])) # Replace 'your_file.csv' with your file name

# Show the first 5 rows of the dataframe
print(df.head(5))


# Export the dataframe to a new CSV file
df.to_csv('exported_data.csv', index=False)

# Download the exported CSV file
files.download('exported_data.csv')

df.info()